environment:
  name: dev
  targetRevision: dev
  project: default
  repoURL: https://github.com/tunghauvan/inf-chart.git
  server: https://kubernetes.default.svc
  chartTargetRevision: dev
  chartRepoURL: https://github.com/tunghauvan/inf-chart.git
  chartPath: charts/generic
  extra_sources:
    - ref: global_service_value
      repoURL: https://github.com/tunghauvan/inf-chart.git
      targetRevision: dev
      yamlPath: charts/infra/values.yaml

nginx:
  type: application
  uniqueValue: ''
  namespace: dev
  replicaCount: 1
  override_values: []
  data: {}
  image:
    tag: "latest"