apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy | default "Forbid" }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit | default 3 }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit | default 1 }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "chart.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- if .Values.enableServiceLinks }}
          enableServiceLinks: {{ .Values.enableServiceLinks }}
          {{- end }}
          containers:
            - name: {{ .Values.appName }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              envFrom:
                {{- if .Values.configs }}
                {{- if .Values.configs.data }}
                - configMapRef:
                    name: {{ .Release.Name }}
                {{- end }}
                {{- end }}
                {{- if and .Values.secrets .Values.secrets.data }}
                - secretRef:
                    name: {{ .Release.Name }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 14 }}
              {{- end }}
              {{- with .Values.startupProbe }}
              startupProbe:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.livenessProbe }}
              livenessProbe:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.readinessProbe }}
              readinessProbe:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
            - name: config-map
              configMap:
                name: {{ .Release.Name }}
                defaultMode: 420
            {{- if .Values.persistence }}
            {{- if .Values.persistence.enabled }}
            - name: {{ .Release.Name }}-data
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-data-pvc
            {{- end }}
            {{- end }}
            {{- with .Values.volumes }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.hostAliases }}
          {{- if .Values.hostAliases.enabled }}
          hostAliases:
            {{- range .Values.hostAliases.aliases }}
            - ip: {{ .ip }}
              hostnames:
                {{- toYaml .hostnames | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- end }}
