{{- if and .Values.nodePortServices .Values.nodePortServices.enabled (not (empty .Values.nodePortServices.ports)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodeport
  labels:
    app: {{ .Values.appName }}
spec:
  type: NodePort
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- range .Values.nodePortServices.ports }}
    - name: {{ .serviceName }}
      port: {{ .exposedPort }}
      targetPort: {{ .exposedPort }}
      nodePort: {{ .nodePort }}
      targetPort: {{ .containerPort }}
  {{- end }}
{{- end }}
