{{- if .Values.secrets }}
{{- if .Values.secrets.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
# Get the values from .Values.secrets.data
{{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end -}}
{{- end -}}