apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
{{- range $service := .Values.services }}
    - port: {{ $service.exposedPort }}
      targetPort: {{ $service.containerPort }}
      protocol: TCP
      name: {{ $service.serviceName }}
{{- end }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
